### ISSUE TITLE
Support mruby 3

### ISSUE THREAD

**Issue by chenrui333** [fourmond/QSoas#4]
👋 it looks like the project cannot be built with mruby 3

```
src/mruby.cc:90:11: error: use of undeclared identifier 'mrb_vm_const_get'
  cTime = mrb_vm_const_get(mrb, mrb_intern_lit(mrb, "Time"));
          ^
          
:615:10: error: use of undeclared identifier 'mrb_to_flo'
  return mrb_to_flo(mrb, value);
         ^
         
          
```

relates to https://github.com/Homebrew/homebrew-core/pull/126912

**Comment by fourmond** [comment]
You are lucky, because the compilation and most of the runtime problems with mruby 3.1 are fixed in the latest commit (a7cef10). Please try this one out and let me know.

The latest release doesn't include this code, since the support is recent and not fully tested -- and some things appear not to work like I would like to.

**Comment by fourmond** [comment]
Just for the record, mruby 3.0 is not supported and probably will not be. 2.1 is now fully supported (with all tests passing). 3.2 is not supported yet, but I plan on making that work reasonably soon.

**Comment by fourmond** [comment]
And now 3.2 is supported with eec9d8c.
